// Source-pixel metadata for the current local metal photographs.
// Generated by scripts/build-metal-masks.py; re-author if a source is replaced.
// PNGs define visible printing. Paths are simplified pointer hit targets only.
export const METAL_SURFACES = {
  'keychain-metal-love': {
    width: 1254, height: 1254,
    sourceSha256: 'd3e3e64510715475d0eaa4170064bfdd8eb5818e25e297dae2e17c45ace979eb',
    regions: [
      {
        id: 'left', photo: 0, maskUrl: '/keychains/metal-love-left-mask.png',
        frame: { x: 158, y: 523, width: 401, height: 395 },
        path: [
          'M158.5 637 L162.5 612 L168.5 592 L180.5 569 L193.5 552 L218.5 533',
          'L220.5 534 L237.5 527 L263.5 524 L287.5 527 L301.5 531 L309.5 536',
          'L311.5 535 L332.5 549 L350.5 566 L360.5 571 L374.5 568 L406.5 542',
          'L432.5 532 L447.5 529 L469.5 529 L487.5 532 L504.5 538 L516.5 546',
          'L539.5 573 L553.5 606 L558.5 635 L558.5 661 L554.5 690 L542.5 727',
          'L528.5 755 L502.5 793 L468.5 832 L464.5 841 L450.5 855 L408.5 889',
          'L365.5 917 L350.5 916 L344.5 913 L309.5 887 L262.5 846 L221.5 802',
          'L195.5 766 L175.5 729 L165.5 702 L158.5 662 Z',
        ].join(' '),
      },
      {
        id: 'right', photo: 1, maskUrl: '/keychains/metal-love-right-mask.png',
        frame: { x: 652, y: 539, width: 400, height: 413 },
        path: [
          'M652.5 673 L656.5 645 L665.5 615 L674.5 596 L688.5 578 L717.5 552',
          'L732.5 545 L759.5 540 L784.5 543 L804.5 550 L832.5 572 L850.5 592',
          'L858.5 596 L874.5 594 L901.5 575 L934.5 562 L967.5 560 L1000.5 569',
          'L1021.5 586 L1035.5 606 L1043.5 624 L1050.5 658 L1050.5 686 L1043.5 723',
          'L1023.5 770 L1003.5 801 L970.5 842 L903.5 899 L853.5 933 L819.5 951',
          'L807.5 951 L793.5 941 L742.5 887 L707.5 840 L683.5 799 L665.5 757',
          'L655.5 718 L652.5 691 Z',
        ].join(' '),
      },
    ],
  },
  'keychain-metal-square': {
    width: 1254, height: 1254,
    sourceSha256: 'c9355e5961fd7208240adf7fa35997cb37c85ef2b3ced8765924bbf82ddb7bfb',
    regions: [{
      id: 'face', photo: 'active', maskUrl: '/keychains/metal-square-mask.png',
      frame: { x: 407, y: 587, width: 447, height: 422 },
      path: [
        'M407.5 905 L409.5 601 L415.5 591 L422.5 588 L835.5 587 L845.5 592',
        'L849.5 600 L852.5 934 L852.5 993 L850.5 1000 L845.5 1006 L832.5 1009',
        'L421.5 1009 L413.5 1006 L407.5 995 Z',
      ].join(' '),
    }],
  },
  'keychain-metal-rectangle': {
    width: 1254, height: 1254,
    sourceSha256: '97c64f2ef5e6109013809f5fcb3d96c913fa9211e3cbc48757d59bd86251e9cc',
    regions: [{
      id: 'face', photo: 'active', maskUrl: '/keychains/metal-rectangle-mask.png',
      frame: { x: 478, y: 563, width: 306, height: 504 },
      path: [
        'M479.5 576 L485.5 568 L490.5 566 L612.5 565 L613.5 596 L620.5 601',
        'L631.5 602 L640.5 598 L641.5 564 L768.5 564 L777.5 569 L780.5 577',
        'L782.5 936 L782.5 1053 L778.5 1062 L765.5 1066 L489.5 1066 L482.5 1061 L479.5 1053 Z',
      ].join(' '),
    }],
  },
  'keychain-metal-hexagon': {
    width: 1254, height: 1254,
    sourceSha256: '2d1351ea3b0c44c1f05edcfd4f009ffa41878b83cec5a00ae4e39c0442bc1591',
    regions: [{
      id: 'face', photo: 'active', maskUrl: '/keychains/metal-hexagon-mask.png',
      frame: { x: 363, y: 570, width: 522, height: 448 },
      path: [
        'M364.5 792 L488.5 587 L500.5 571 L754.5 573 L883.5 790 L883.5 797',
        'L801.5 939 L754.5 1015 L749.5 1017 L496.5 1017 L490.5 1010 L375.5 817 L364.5 795 Z',
      ].join(' '),
    }],
  },
} as const;